<?php
declare(strict_types=1);

session_start();

/*
|--------------------------------------------------------------------------
| Simple FoundryPress Installer
|--------------------------------------------------------------------------
| Place this file in the ROOT of the site:
| /install.php
|
| It writes:
|   /config/site.php
|   /license.json
|
| After successful install, you should delete or lock this installer.
|--------------------------------------------------------------------------
*/

function h(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

function detect_scheme(): string
{
    if (
        (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (isset($_SERVER['SERVER_PORT']) && (string) $_SERVER['SERVER_PORT'] === '443')
    ) {
        return 'https';
    }

    return 'http';
}

function detect_host(): string
{
    return $_SERVER['HTTP_HOST'] ?? 'localhost';
}

function detect_base_url(): string
{
    $scheme = detect_scheme();
    $host   = detect_host();

    return $scheme . '://' . $host;
}

function ensure_dir(string $path): bool
{
    if (is_dir($path)) {
        return true;
    }

    return mkdir($path, 0755, true);
}

function write_php_config(array $data, string $targetFile): bool
{
    $siteName       = var_export($data['site_name'], true);
    $brandName      = var_export($data['brand_name'], true);
    $baseUrl        = var_export($data['base_url'], true);
    $adminUsername  = var_export($data['admin_username'], true);
    $passwordHash   = var_export($data['admin_password_hash'], true);
    $installedAt    = var_export($data['installed_at'], true);

    $php = <<<PHP
<?php
declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| FoundryPress Site Config
|--------------------------------------------------------------------------
| This file is generated by install.php
|--------------------------------------------------------------------------
*/

define('FP_INSTALLED', true);
define('FP_SITE_NAME', {$siteName});
define('FP_BRAND_NAME', {$brandName});
define('FP_BASE_URL', {$baseUrl});
define('FP_ADMIN_USERNAME', {$adminUsername});
define('FP_ADMIN_PASSWORD_HASH', {$passwordHash});
define('FP_INSTALLED_AT', {$installedAt});

PHP;

    return file_put_contents($targetFile, $php) !== false;
}

function write_license_json(array $data, string $targetFile): bool
{
    $payload = [
        'license_key'  => $data['license_key'],
        'domain'       => parse_url($data['base_url'], PHP_URL_HOST) ?: '',
        'status'       => $data['license_key'] !== '' ? 'active' : 'unlicensed',
        'installed_at' => $data['installed_at'],
        'last_check'   => null,
    ];

    $json = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

    return $json !== false && file_put_contents($targetFile, $json) !== false;
}

$rootPath       = __DIR__;
$configDir      = $rootPath . '/config';
$siteConfigFile = $configDir . '/site.php';
$licenseFile    = $rootPath . '/license.json';

$alreadyInstalled = file_exists($siteConfigFile);

$errors = [];
$success = false;

$defaults = [
    'site_name'      => 'FoundryPress Site',
    'brand_name'     => 'My Brand',
    'base_url'       => detect_base_url(),
    'admin_username' => 'admin',
    'license_key'    => '',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$alreadyInstalled) {
    $siteName       = trim((string) ($_POST['site_name'] ?? ''));
    $brandName      = trim((string) ($_POST['brand_name'] ?? ''));
    $baseUrl        = trim((string) ($_POST['base_url'] ?? ''));
    $adminUsername  = trim((string) ($_POST['admin_username'] ?? ''));
    $adminPassword  = (string) ($_POST['admin_password'] ?? '');
    $confirmPassword = (string) ($_POST['confirm_password'] ?? '');
    $licenseKey     = trim((string) ($_POST['license_key'] ?? ''));

    $defaults = [
        'site_name'      => $siteName,
        'brand_name'     => $brandName,
        'base_url'       => $baseUrl,
        'admin_username' => $adminUsername,
        'license_key'    => $licenseKey,
    ];

    if ($siteName === '') {
        $errors[] = 'Site name is required.';
    }

    if ($brandName === '') {
        $errors[] = 'Brand name is required.';
    }

    if ($baseUrl === '') {
        $errors[] = 'Base URL is required.';
    } elseif (!filter_var($baseUrl, FILTER_VALIDATE_URL)) {
        $errors[] = 'Base URL must be a valid URL.';
    }

    if ($adminUsername === '') {
        $errors[] = 'Admin username is required.';
    }

    if ($adminPassword === '') {
        $errors[] = 'Admin password is required.';
    } elseif (strlen($adminPassword) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }

    if ($adminPassword !== $confirmPassword) {
        $errors[] = 'Password confirmation does not match.';
    }

    if (!ensure_dir($configDir)) {
        $errors[] = 'Could not create the /config directory.';
    }

    if (empty($errors)) {
        $installedAt = date(DATE_ATOM);
        $passwordHash = password_hash($adminPassword, PASSWORD_DEFAULT);

        if ($passwordHash === false) {
            $errors[] = 'Could not hash the admin password.';
        } else {
            $configWritten = write_php_config([
                'site_name'           => $siteName,
                'brand_name'          => $brandName,
                'base_url'            => rtrim($baseUrl, '/'),
                'admin_username'      => $adminUsername,
                'admin_password_hash' => $passwordHash,
                'installed_at'        => $installedAt,
            ], $siteConfigFile);

            if (!$configWritten) {
                $errors[] = 'Could not write config/site.php. Check file permissions.';
            } else {
                $licenseWritten = write_license_json([
                    'license_key'  => $licenseKey,
                    'base_url'     => rtrim($baseUrl, '/'),
                    'installed_at' => $installedAt,
                ], $licenseFile);

                if (!$licenseWritten) {
                    $errors[] = 'Could not write license.json. Check file permissions.';
                } else {
                    $success = true;
                    $alreadyInstalled = true;
                }
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install FoundryPress</title>
    <style>
        :root {
            --bg: #f6f4ef;
            --panel: #ffffff;
            --text: #1f2328;
            --muted: #5f6b76;
            --border: #d9d3c7;
            --accent: #7c8f6a;
            --accent-dark: #5f7150;
            --danger-bg: #fff3f0;
            --danger-border: #e4b4a8;
            --success-bg: #eef7ea;
            --success-border: #b8d2ae;
        }

        * { box-sizing: border-box; }

        body {
            margin: 0;
            background: var(--bg);
            color: var(--text);
            font-family: Inter, Arial, sans-serif;
            line-height: 1.5;
        }

        .wrap {
            max-width: 760px;
            margin: 40px auto;
            padding: 20px;
        }

        .card {
            background: var(--panel);
            border: 1px solid var(--border);
            border-radius: 18px;
            padding: 28px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.04);
        }

        h1 {
            margin-top: 0;
            font-size: 2rem;
            line-height: 1.1;
        }

        p.lead {
            color: var(--muted);
            margin-top: 0;
            margin-bottom: 24px;
        }

        .notice,
        .success {
            border-radius: 14px;
            padding: 14px 16px;
            margin-bottom: 18px;
        }

        .notice {
            background: var(--danger-bg);
            border: 1px solid var(--danger-border);
        }

        .success {
            background: var(--success-bg);
            border: 1px solid var(--success-border);
        }

        .notice ul {
            margin: 0;
            padding-left: 20px;
        }

        .grid {
            display: grid;
            gap: 16px;
        }

        @media (min-width: 720px) {
            .grid.two {
                grid-template-columns: 1fr 1fr;
            }
        }

        label {
            display: block;
            font-weight: 600;
            margin-bottom: 6px;
        }

        input {
            width: 100%;
            padding: 12px 14px;
            border: 1px solid var(--border);
            border-radius: 12px;
            font: inherit;
            background: #fff;
        }

        .help {
            font-size: 0.92rem;
            color: var(--muted);
            margin-top: 6px;
        }

        .actions {
            margin-top: 24px;
        }

        button,
        .button-link {
            display: inline-block;
            border: 0;
            border-radius: 999px;
            background: var(--accent);
            color: #fff;
            padding: 12px 18px;
            font: inherit;
            font-weight: 700;
            text-decoration: none;
            cursor: pointer;
        }

        button:hover,
        .button-link:hover {
            background: var(--accent-dark);
        }

        code {
            background: #f1ede4;
            padding: 2px 6px;
            border-radius: 6px;
        }
    </style>
</head>
<body>
<div class="wrap">
    <div class="card">
        <h1>Install FoundryPress</h1>
        <p class="lead">
            This installer will create your site config and license file so the Hub can run on this domain.
        </p>

        <?php if ($alreadyInstalled && !$success): ?>
            <div class="success">
                <strong>FoundryPress already appears to be installed.</strong><br>
                The installer found <code>/config/site.php</code>.
            </div>

            <p>
                For security, you should delete or disable <code>install.php</code> after setup.
            </p>

            <p>
                <a class="button-link" href="/hub/login.php">Go to Hub Login</a>
            </p>

        <?php elseif ($success): ?>
            <div class="success">
                <strong>Installation complete.</strong><br>
                Your config and license files were created successfully.
            </div>

            <p>
                Next step: delete or disable <code>install.php</code> so clients cannot rerun it.
            </p>

            <p>
                <a class="button-link" href="/hub/login.php">Go to Hub Login</a>
            </p>

        <?php else: ?>

            <?php if (!empty($errors)): ?>
                <div class="notice">
                    <strong>Please fix the following:</strong>
                    <ul>
                        <?php foreach ($errors as $error): ?>
                            <li><?= h($error) ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <form method="post" action="">
                <div class="grid two">
                    <div>
                        <label for="site_name">Site Name</label>
                        <input id="site_name" name="site_name" type="text" value="<?= h($defaults['site_name']) ?>" required>
                    </div>

                    <div>
                        <label for="brand_name">Brand Name</label>
                        <input id="brand_name" name="brand_name" type="text" value="<?= h($defaults['brand_name']) ?>" required>
                    </div>
                </div>

                <div class="grid" style="margin-top:16px;">
                    <div>
                        <label for="base_url">Base URL</label>
                        <input id="base_url" name="base_url" type="url" value="<?= h($defaults['base_url']) ?>" required>
                        <div class="help">Example: https://example.com</div>
                    </div>
                </div>

                <div class="grid two" style="margin-top:16px;">
                    <div>
                        <label for="admin_username">Admin Username</label>
                        <input id="admin_username" name="admin_username" type="text" value="<?= h($defaults['admin_username']) ?>" required>
                    </div>

                    <div>
                        <label for="license_key">License Key</label>
                        <input id="license_key" name="license_key" type="text" value="<?= h($defaults['license_key']) ?>">
                        <div class="help">Optional for now. You can validate it later.</div>
                    </div>
                </div>

                <div class="grid two" style="margin-top:16px;">
                    <div>
                        <label for="admin_password">Admin Password</label>
                        <input id="admin_password" name="admin_password" type="password" required>
                    </div>

                    <div>
                        <label for="confirm_password">Confirm Password</label>
                        <input id="confirm_password" name="confirm_password" type="password" required>
                    </div>
                </div>

                <div class="actions">
                    <button type="submit">Install FoundryPress</button>
                </div>
            </form>

        <?php endif; ?>
    </div>
</div>
</body>
</html>